In [1]:
from datascience import *

In [2]:
make_array(42, 43, 44)

array([42, 43, 44])

In [3]:
type(make_array(42, 43, 44))

numpy.ndarray

In [4]:
pokemon_i_like = make_array('Pikachu', 'Charizard', "Squirtle")

In [6]:
pokemon_i_like

array(['Pikachu', 'Charizard', 'Squirtle'],
      dtype='<U9')

In [7]:
len(pokemon_i_like)

3

In [8]:
pokemon_i_like.item(0)

'Pikachu'

In [9]:
pokemon_i_like.item(1)

'Charizard'

In [10]:
temps_f = make_array(100, 78, 32, -40)

In [11]:
temps_f * 2

array([200, 156,  64, -80])

In [12]:
len(temps_f)

4

In [13]:
temps_f.size

4

In [14]:
temps_f.sum()

170

In [15]:
temps_f.mean()

42.5

In [16]:
import numpy as np

In [17]:
np.diff(temps_f)

array([-22, -46, -72])

In [19]:
temps_c = (temps_f - 32) * (5/9)
temps_c

array([ 37.77777778,  25.55555556,   0.        , -40.        ])

In [20]:
np.round(temps_c, 2)

array([ 37.78,  25.56,   0.  , -40.  ])

In [21]:
2 < 3

True

In [22]:
True + False + True

2

In [23]:
make_array(1 < 2, 2 < 1, 8 < 7, 42 < 43)

array([1, 0, 0, 1])

In [24]:
np.count_nonzero(make_array(1 < 2, 2 < 1, 8 < 7, 42 < 43))

2

In [25]:
pokemon_i_like

array(['Pikachu', 'Charizard', 'Squirtle'],
      dtype='<U9')

In [26]:
np.char.upper(pokemon_i_like)

array(['PIKACHU', 'CHARIZARD', 'SQUIRTLE'],
      dtype='<U9')

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.arange(1, 101)   # [1, 2, ..., 100]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [40]:
np.arange(13, 11.9, -0.1)

array([ 13. ,  12.9,  12.8,  12.7,  12.6,  12.5,  12.4,  12.3,  12.2,
        12.1,  12. ])

In [41]:
pos_denoms = np.arange(1, 10000, 4)
pos_denoms

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [42]:
neg_denoms = np.arange(3, 10000, 4)
neg_denoms

array([   3,    7,   11, ..., 9991, 9995, 9999])

In [44]:
pos_terms = 1 / pos_denoms
neg_terms = 1 / neg_denoms

In [45]:
pos_terms

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00110121e-04,   1.00070049e-04,   1.00030009e-04])

In [46]:
4 * (sum(pos_terms) - sum(neg_terms))

3.1413926535917955

---

In [47]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70             | 634        | 45           | Flame Pokémon       | 78      | 1059860           | 1.7      | 78   | Lizardonリザードン    | Charizard  | 88.1            | 6              | 159       | 115        | 100   | fire  | flying | 90.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 48     | 5120           | 70             | 314        | 45           | Tiny Turtle Pokémon | 65      | 1059860           | 0.5      | 44   | Zenigameゼニガメ     | Squirtle   | 88.1            | 7              | 50        | 64         | 43    | water | nan    | 9         | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 63     | 5120           | 70             | 405        | 45           | Turtle Pokémon      | 80      | 1059860           | 1        | 59   | Kameilカメール       | Wartortle  | 88.1            | 8              | 65        | 80         | 58    | water | nan    | 22.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 103    | 5120           | 70             | 630        | 45           | Shellfish Pokémon   | 120     | 1059860           | 1.6      | 79   | Kamexカメックス       | Blastoise  | 88.1            | 9              | 135       | 115        | 78    | water | nan    | 85.5      | 1          | 0
['Shield Dust', 'Run Away'] | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 30     | 3840           | 70             | 195        | 255          | Worm Pokémon        | 35      | 1000000           | 0.3      | 45   | Caterpieキャタピー    | Caterpie   | 50              | 10             | 20        | 20         | 45    | bug   | nan    | 2.9       | 1          | 0
... (791 rows omitted)

In [48]:
pokemon.select('name')

name
Bulbasaur
Ivysaur
Venusaur
Charmander
Charmeleon
Charizard
Squirtle
Wartortle
Blastoise
Caterpie
... (791 rows omitted)

In [49]:
pokemon.column('name')

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey',
       'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow',
       'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash',
       'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino',
       'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales',
       'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom',
       'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett',
       'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey',
       'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl',
       'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', "Farfetch'd",
       'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder',
       'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee',
       'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking',
       'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz',
       'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras',
       'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon',
       'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu',
       'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom', 'Marill', 'Azumarill',
       'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom',
       'Sunkern', 'Sunflora', 'Yanma', 'Wooper', 'Quagsire', 'Espeon',
       'Umbreon', 'Murkrow', 'Slowking', 'Misdreavus', 'Unown',
       'Wobbuffet', 'Girafarig', 'Pineco', 'Forretress', 'Dunsparce',
       'Gligar', 'Steelix', 'Snubbull', 'Granbull', 'Qwilfish', 'Scizor',
       'Shuckle', 'Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
       'Slugma', 'Magcargo', 'Swinub', 'Piloswine', 'Corsola', 'Remoraid',
       'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
       'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 'Stantler',
       'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid', 'Magby',
       'Miltank', 'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar',
       'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi', 'Treecko',
       'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken', 'Mudkip',
       'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon',
       'Linoone', 'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox',
       'Lotad', 'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry',
       'Taillow', 'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia',
       'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom',
       'Slakoth', 'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja',
       'Whismur', 'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill',
       'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron',
       'Lairon', 'Aggron', 'Meditite', 'Medicham', 'Electrike',
       'Manectric', 'Plusle', 'Minun', 'Volbeat', 'Illumise', 'Roselia',
       'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord',
       'Numel', 'Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'Zangoose', 'Seviper', 'Lunatone', 'Solrock', 'Barboach',
       'Whiscash', 'Corphish', 'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep',
       'Cradily', 'Anorith', 'Armaldo', 'Feebas', 'Milotic', 'Castform',
       'Kecleon', 'Shuppet', 'Banette', 'Duskull', 'Dusclops', 'Tropius',
       'Chimecho', 'Absol', 'Wynaut', 'Snorunt', 'Glalie', 'Spheal',
       'Sealeo', 'Walrein', 'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth',
       'Luvdisc', 'Bagon', 'Shelgon', 'Salamence', 'Beldum', 'Metang',
       'Metagross', 'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios',
       'Kyogre', 'Groudon', 'Rayquaza', 'Jirachi', 'Deoxys', 'Turtwig',
       'Grotle', 'Torterra', 'Chimchar', 'Monferno', 'Infernape', 'Piplup',
       'Prinplup', 'Empoleon', 'Starly', 'Staravia', 'Staraptor', 'Bidoof',
       'Bibarel', 'Kricketot', 'Kricketune', 'Shinx', 'Luxio', 'Luxray',
       'Budew', 'Roserade', 'Cranidos', 'Rampardos', 'Shieldon',
       'Bastiodon', 'Burmy', 'Wormadam', 'Mothim', 'Combee', 'Vespiquen',
       'Pachirisu', 'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos',
       'Gastrodon', 'Ambipom', 'Drifloon', 'Drifblim', 'Buneary',
       'Lopunny', 'Mismagius', 'Honchkrow', 'Glameow', 'Purugly',
       'Chingling', 'Stunky', 'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly',
       'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb', 'Gible', 'Gabite',
       'Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Hippopotas',
       'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak',
       'Carnivine', 'Finneon', 'Lumineon', 'Mantyke', 'Snover',
       'Abomasnow', 'Weavile', 'Magnezone', 'Lickilicky', 'Rhyperior',
       'Tangrowth', 'Electivire', 'Magmortar', 'Togekiss', 'Yanmega',
       'Leafeon', 'Glaceon', 'Gliscor', 'Mamoswine', 'Porygon-Z',
       'Gallade', 'Probopass', 'Dusknoir', 'Froslass', 'Rotom', 'Uxie',
       'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran', 'Regigigas',
       'Giratina', 'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin',
       'Arceus', 'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig',
       'Pignite', 'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat',
       'Watchog', 'Lillipup', 'Herdier', 'Stoutland', 'Purrloin',
       'Liepard', 'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino', 'Timburr',
       'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad',
       'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede',
       'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil',
       'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile',
       'Darumaka', 'Darmanitan', 'Maractus', 'Dwebble', 'Crustle',
       'Scraggy', 'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus',
       'Tirtouga', 'Carracosta', 'Archen', 'Archeops', 'Trubbish',
       'Garbodor', 'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita',
       'Gothorita', 'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus',
       'Ducklett', 'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe',
       'Deerling', 'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier',
       'Foongus', 'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola',
       'Joltik', 'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink', 'Klang',
       'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross', 'Elgyem',
       'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew', 'Fraxure',
       'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet', 'Accelgor',
       'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon', 'Golett', 'Golurk',
       'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet', 'Braviary',
       'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino', 'Zweilous',
       'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion', 'Terrakion',
       'Virizion', 'Tornadus', 'Thundurus', 'Reshiram', 'Zekrom',
       'Landorus', 'Kyurem', 'Keldeo', 'Meloetta', 'Genesect', 'Chespin',
       'Quilladin', 'Chesnaught', 'Fennekin', 'Braixen', 'Delphox',
       'Froakie', 'Frogadier', 'Greninja', 'Bunnelby', 'Diggersby',
       'Fletchling', 'Fletchinder', 'Talonflame', 'Scatterbug', 'Spewpa',
       'Vivillon', 'Litleo', 'Pyroar', 'Flabébé', 'Floette', 'Florges',
       'Skiddo', 'Gogoat', 'Pancham', 'Pangoro', 'Furfrou', 'Espurr',
       'Meowstic', 'Honedge', 'Doublade', 'Aegislash', 'Spritzee',
       'Aromatisse', 'Swirlix', 'Slurpuff', 'Inkay', 'Malamar', 'Binacle',
       'Barbaracle', 'Skrelp', 'Dragalge', 'Clauncher', 'Clawitzer',
       'Helioptile', 'Heliolisk', 'Tyrunt', 'Tyrantrum', 'Amaura',
       'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy',
       'Sliggoo', 'Goodra', 'Klefki', 'Phantump', 'Trevenant', 'Pumpkaboo',
       'Gourgeist', 'Bergmite', 'Avalugg', 'Noibat', 'Noivern', 'Xerneas',
       'Yveltal', 'Zygarde', 'Diancie', 'Hoopa', 'Volcanion', 'Rowlet',
       'Dartrix', 'Decidueye', 'Litten', 'Torracat', 'Incineroar',
       'Popplio', 'Brionne', 'Primarina', 'Pikipek', 'Trumbeak',
       'Toucannon', 'Yungoos', 'Gumshoos', 'Grubbin', 'Charjabug',
       'Vikavolt', 'Crabrawler', 'Crabominable', 'Oricorio', 'Cutiefly',
       'Ribombee', 'Rockruff', 'Lycanroc', 'Wishiwashi', 'Mareanie',
       'Toxapex', 'Mudbray', 'Mudsdale', 'Dewpider', 'Araquanid',
       'Fomantis', 'Lurantis', 'Morelull', 'Shiinotic', 'Salandit',
       'Salazzle', 'Stufful', 'Bewear', 'Bounsweet', 'Steenee', 'Tsareena',
       'Comfey', 'Oranguru', 'Passimian', 'Wimpod', 'Golisopod',
       'Sandygast', 'Palossand', 'Pyukumuku', 'Type: Null', 'Silvally',
       'Minior', 'Komala', 'Turtonator', 'Togedemaru', 'Mimikyu',
       'Bruxish', 'Drampa', 'Dhelmise', 'Jangmo-o', 'Hakamo-o', 'Kommo-o',
       'Tapu Koko', 'Tapu Lele', 'Tapu Bulu', 'Tapu Fini', 'Cosmog',
       'Cosmoem', 'Solgaleo', 'Lunala', 'Nihilego', 'Buzzwole',
       'Pheromosa', 'Xurkitree', 'Celesteela', 'Kartana', 'Guzzlord',
       'Necrozma', 'Magearna'],
      dtype='<U12')

In [51]:
attacks = pokemon.column('attack')
attacks

array([ 49,  62, 100,  52,  64, 104,  48,  63, 103,  30,  20,  45,  35,
        25, 150,  45,  60,  80,  56,  71,  60,  90,  60,  95,  55,  85,
        75, 100,  47,  62,  92,  57,  72, 102,  45,  70,  41,  67,  45,
        70,  45,  80,  50,  65,  80,  70,  95,  55,  65,  55, 100,  35,
        60,  52,  82,  80, 105,  70, 110,  50,  65,  95,  20,  35,  50,
        80, 100, 130,  75,  90, 105,  40,  70,  80,  95, 120,  85, 100,
        65,  75,  35,  60,  90,  85, 110,  45,  70,  80, 105,  65,  95,
        35,  50,  65,  45,  48,  73, 105, 130,  30,  50,  40, 105,  50,
        80, 120, 105,  55,  65,  90,  85, 130,   5,  55, 125,  40,  65,
        67,  92,  45,  75,  45, 110,  50,  83,  95, 155, 100,  10, 155,
        85,  48,  55,  65,  65, 130,  60,  40,  60,  80, 115, 135, 110,
        85,  90, 100,  64,  84, 134, 150, 100,  49,  62,  82,  52,  64,
        84,  65,  80, 105,  46,  76,  30,  50,  20,  35,  60,  90,  90,
        38,  58,  40,  25,  30,  20,  40,  50,  75,  40,  55,  95,  80,
        20,  50, 100,  75,  35,  45,  55,  70,  30,  75,  65,  45,  85,
        65,  65,  85,  75,  60,  72,  33,  80,  65,  90,  70,  75, 125,
        80, 120,  95, 150,  10, 185,  95,  80, 130,  40,  50,  50, 100,
        55,  65, 105,  55,  40,  80,  60,  90,  95,  60, 120,  80,  95,
        20,  35,  95,  30,  63,  75,  80,  10,  85, 115,  75,  64,  84,
       164,  90, 130, 100,  45,  65, 110,  60,  85, 160,  70,  85, 150,
        55,  90,  30,  70,  45,  35,  70,  35,  50,  30,  50,  70,  40,
        70, 100,  55,  85,  30,  50,  25,  35,  85,  30,  60,  40, 130,
        60,  80, 160,  45,  90,  90,  51,  71,  91,  60, 120,  20,  45,
        45,  65,  85, 105,  70,  90, 140,  40, 100,  45,  75,  50,  40,
        73,  47,  60,  43,  73,  90, 140,  70,  90,  60, 120,  85,  25,
        45,  60, 100,  70, 100,  85, 115,  40, 110, 115, 100,  55,  95,
        48,  78,  80, 120,  40,  70,  41,  81,  95, 125,  15,  60,  70,
        90,  75, 165,  40,  70,  68,  50, 150,  23,  50, 120,  40,  60,
        80,  64, 104,  84,  90,  30,  75,  95, 145,  55,  75, 145, 100,
        50,  75, 100, 130, 150, 180, 180, 100,  95,  68,  89, 109,  58,
        78, 104,  51,  66,  86,  55,  75, 120,  45,  85,  25,  85,  65,
        85, 120,  30,  70, 125, 165,  42,  52,  29,  69,  94,  30,  80,
        45,  65, 105,  35,  60,  48,  83, 100,  50,  80,  66, 136,  60,
       125,  55,  82,  30,  63,  93,  24,  89,  80,  25,   5,  65,  92,
        70,  90, 170,  85,  70, 145,  72, 112,  50,  90,  61, 106, 100,
        49,  69,  20,  62, 132, 120,  70,  85, 140, 100, 123,  95,  50,
        76, 110,  60,  95, 130,  80, 165,  55, 100,  80,  65,  75, 105,
       125, 120, 120,  90, 160, 120,  70,  80, 100,  90, 103, 120, 100,
        45,  60,  75,  63,  93, 123,  55,  75, 100,  55,  85,  60,  80,
       110,  50,  88,  53,  98,  53,  98,  53,  98,  25,  55,  55,  77,
       115,  60, 100,  75, 105, 135,  45,  57,  85, 135,  60,  80, 105,
       140,  50,  65,  95, 100, 125,  53,  63, 103,  45,  55, 100,  27,
        67,  35,  60,  92,  72,  82, 117,  90,  30,  86,  65, 105,  75,
        90,  58,  30,  50,  78, 108, 112, 140,  50,  95,  65, 105,  50,
        95,  30,  45,  55,  30,  40,  65,  44,  87,  50,  65,  95,  60,
       100,  75,  75, 135,  55,  85,  40,  60,  75,  47,  77,  50,  94,
        55,  80, 100,  55,  85, 115,  55,  75,  30,  40,  55,  87, 117,
       147,  70, 130,  50,  40,  70,  66,  85, 125, 120,  74, 124,  85,
       125, 110,  83, 123,  55,  65,  97, 109,  65,  85, 105,  85,  60,
        90, 129,  90, 100, 105, 120, 150, 145, 120,  72, 128, 120,  61,
        78, 107,  45,  59,  69,  56,  63, 145,  36,  56,  50,  73,  81,
        35,  22,  52,  50,  68,  38,  65,  65,  65, 100,  82, 124,  80,
        48,  48,  80, 110, 150,  52,  72,  48,  80,  54,  92,  52, 105,
        60,  75,  53,  73,  38,  55,  89, 121,  59,  77,  65,  92,  58,
        50,  50,  75, 100,  80,  70, 110,  66, 100,  69, 117,  30,  70,
       131, 131, 100, 160, 160, 110,  55,  75, 107,  65,  85, 115,  54,
        69,  74,  75,  85, 120,  70, 110,  62,  82,  70,  82, 132,  70,
        45,  55,  65, 115, 140,  53,  63, 100, 125,  40,  70,  55, 105,
        35,  45,  44,  64,  75, 125,  30,  40, 120,  52,  60, 120,  35,
       125,  55,  75,  60,  95,  95, 100, 115,  78,  98,  90, 105,  60,
       131,  55,  75, 110, 115,  85, 130,  75,  29,  29, 137, 113,  53,
       139, 137,  89, 101, 181, 101, 107,  95])

In [52]:
attacks.mean()

77.857677902621717

In [53]:
np.mean(attacks)

77.857677902621717

In [54]:
np.average(attacks)

77.857677902621717

In [55]:
sum(attacks) / len(attacks)

77.857677902621717

# Miscellaneous things Lawton needs to teach you

In [56]:
', '.join(make_array('1', '2', '3'))  # the sequence has to be strs

'1, 2, 3'

In [57]:
' and '.join(make_array('1', '2', '3'))

'1 and 2 and 3'