In [1]:
from datascience import *

In [2]:
Table()  # empty table

In [3]:
Table().with_column('Name', make_array('Lawton', 'Lonzo', 'Bill'))

Name
Lawton
Lonzo
Bill

In [7]:
Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(33, 5, 34)
)

Name   | Age
Lawton | 33
Lonzo  | 5
Bill   | 34

In [8]:
people = Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(33, 5, 34)
)

In [9]:
people

Name   | Age
Lawton | 33
Lonzo  | 5
Bill   | 34

In [11]:
# It's fine to use the plural with_columns and only add a single column
people.with_columns('Employer', make_array("CCC", 'Unemployed', 'CCC'))

Name   | Age  | Employer
Lawton | 33   | CCC
Lonzo  | 5    | Unemployed
Bill   | 34   | CCC

In [13]:
people  # didn't change

Name   | Age
Lawton | 33
Lonzo  | 5
Bill   | 34

In [14]:
people.relabeled('Age', 'Trips around the sun')

Name   | Trips around the sun
Lawton | 33
Lonzo  | 5
Bill   | 34

In [15]:
people

Name   | Age
Lawton | 33
Lonzo  | 5
Bill   | 34

---

In [17]:
cones = Table.read_table('data/cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [18]:
cones.num_columns

3

In [19]:
cones.num_rows

7

In [20]:
cones.labels

('Flavor', 'Color', 'Price')

In [21]:
cones.column('Price')

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [22]:
cones.column(2)

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [23]:
cones.column('Price').item(3)

3.5

In [24]:
cones.column('Price').item(0)  # first one is at index 0

3.55

In [25]:
# Crushed ICE: calculate the total price after applying 8.75% sales tax to the Price column

In [29]:
# option 1
tax = cones.column('Price') * (8.75 / 100)
tax + cones.column('Price')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [31]:
# option 2
import numpy as np
np.round(cones.column('Price') * 1.0875, 2)

array([ 3.86,  5.17,  5.71,  3.81,  5.71,  5.71,  5.17])

In [36]:
tax_rate = 0.0875
tax = cones.column('Price') * tax_rate
cones_with_tax = cones.with_column('Price with tax', tax + cones.column('Price'))
cones_with_tax

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | 3.86062
chocolate  | light brown | 4.75  | 5.16563
chocolate  | dark brown  | 5.25  | 5.70937
vanilla    | white       | 3.5   | 3.80625
strawberry | pink        | 5.25  | 5.70937
chocolate  | dark brown  | 5.25  | 5.70937
bubblegum  | pink        | 4.75  | 5.16563

In [37]:
cones_with_tax.set_format('Price with tax', CurrencyFormatter)

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [39]:
cones_with_tax.column('Price with tax')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [40]:
Table().with_column('x', make_array(1000, 10000, 9999999999999)).set_format('x', NumberFormatter)

x
1,000
10,000
9,999,999,999,999

In [41]:
Table().with_column('x', make_array(0.5, 0.75, 0.9999)).set_format('x', PercentFormatter)

x
50.00%
75.00%
99.99%

In [42]:
cones_with_tax

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [45]:
cones_with_tax.select('Flavor', 'Price with tax')

Flavor     | Price with tax
strawberry | $3.86
chocolate  | $5.17
chocolate  | $5.71
vanilla    | $3.81
strawberry | $5.71
chocolate  | $5.71
bubblegum  | $5.17

In [47]:
cones_with_tax.select(0, 3)  # indices work too

Flavor     | Price with tax
strawberry | $3.86
chocolate  | $5.17
chocolate  | $5.71
vanilla    | $3.81
strawberry | $5.71
chocolate  | $5.71
bubblegum  | $5.17

In [48]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum

In [49]:
cones.column('Flavor') # only this one makes an array!

array(['strawberry', 'chocolate', 'chocolate', 'vanilla', 'strawberry',
       'chocolate', 'bubblegum'],
      dtype='<U10')

In [51]:
cones_with_tax.drop('Price') # makes a new Table, as usual

Flavor     | Color       | Price with tax
strawberry | pink        | $3.86
chocolate  | light brown | $5.17
chocolate  | dark brown  | $5.71
vanilla    | white       | $3.81
strawberry | pink        | $5.71
chocolate  | dark brown  | $5.71
bubblegum  | pink        | $5.17

In [53]:
cones_with_tax.sort('Price with tax')

Flavor     | Color       | Price | Price with tax
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
bubblegum  | pink        | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71

In [54]:
cones_with_tax.sort('Price with tax', descending=True)

Flavor     | Color       | Price | Price with tax
chocolate  | dark brown  | 5.25  | $5.71
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
chocolate  | light brown | 4.75  | $5.17
bubblegum  | pink        | 4.75  | $5.17
strawberry | pink        | 3.55  | $3.86
vanilla    | white       | 3.5   | $3.81

In [55]:
cones_with_tax

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [56]:
cones_with_tax.take(4)

Flavor     | Color | Price | Price with tax
strawberry | pink  | 5.25  | $5.71

In [57]:
cones_with_tax.take(1, 3, 5)

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
vanilla   | white       | 3.5   | $3.81
chocolate | dark brown  | 5.25  | $5.71

In [61]:
import numpy as np
cones_with_tax.take(np.arange(1, cones_with_tax.num_rows, 2))  # all the odd indices

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
vanilla   | white       | 3.5   | $3.81
chocolate | dark brown  | 5.25  | $5.71

In [62]:
cones_with_tax

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [63]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [64]:
cones = cones_with_tax  # remember that you can always overwrite an existing Table!

In [65]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [66]:
cones.where('Flavor', are.equal_to('chocolate'))

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [68]:
# by default, you get an equality check. This is equivalent to the line above!
cones.where('Flavor', 'chocolate') # this is shorthand for the one above

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [69]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [70]:
cones.where('Price with tax', are.below_or_equal_to(5))

Flavor     | Color | Price | Price with tax
strawberry | pink  | 3.55  | $3.86
vanilla    | white | 3.5   | $3.81

In [71]:
cones.where('Price with tax', are.below_or_equal_to(5)).sort('Price with tax')

Flavor     | Color | Price | Price with tax
vanilla    | white | 3.5   | $3.81
strawberry | pink  | 3.55  | $3.86

In [72]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [73]:
cones.where('Color', are.containing('brown'))

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [74]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [75]:
cones.show(3)  # shows the first 3 rows. .show() with nothing shows everything!

---

In [76]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70             | 634        | 45           | Flame Pokémon       | 78      | 1059860           | 1.7      | 78   | Lizardonリザードン    | Charizard  | 88.1            | 6              | 159       | 115        | 100   | fire  | flying | 90.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 48     | 5120           | 70             | 314        | 45           | Tiny Turtle Pokémon | 65      | 1059860           | 0.5      | 44   | Zenigameゼニガメ     | Squirtle   | 88.1            | 7              | 50        | 64         | 43    | water | nan    | 9         | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 63     | 5120           | 70             | 405        | 45           | Turtle Pokémon      | 80      | 1059860           | 1        | 59   | Kameilカメール       | Wartortle  | 88.1            | 8              | 65        | 80         | 58    | water | nan    | 22.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 103    | 5120           | 70             | 630        | 45           | Shellfish Pokémon   | 120     | 1059860           | 1.6      | 79   | Kamexカメックス       | Blastoise  | 88.1            | 9              | 135       | 115        | 78    | water | nan    | 85.5      | 1          | 0
['Shield Dust', 'Run Away'] | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 30     | 3840           | 70             | 195        | 255          | Worm Pokémon        | 35      | 1000000           | 0.3      | 45   | Caterpieキャタピー    | Caterpie   | 50              | 10             | 20        | 20         | 45    | bug   | nan    | 2.9       | 1          | 0
... (791 rows omitted)

In [80]:
temp = pokemon.select('name', 'height_m')
temp

name       | height_m
Bulbasaur  | 0.7
Ivysaur    | 1
Venusaur   | 2
Charmander | 0.6
Charmeleon | 1.1
Charizard  | 1.7
Squirtle   | 0.5
Wartortle  | 1
Blastoise  | 1.6
Caterpie   | 0.3
... (791 rows omitted)

In [83]:
temp.where('height_m', are.above_or_equal_to(0)).sort('height_m', descending=True).show(5)

In [87]:
temp = pokemon.select('name', 'speed', 'weight_kg').with_column(
    'speed/weight ratio', pokemon.column('speed') / pokemon.column('weight_kg')
)
temp

name       | speed | weight_kg | speed/weight ratio
Bulbasaur  | 45    | 6.9       | 6.52174
Ivysaur    | 60    | 13        | 4.61538
Venusaur   | 80    | 100       | 0.8
Charmander | 65    | 8.5       | 7.64706
Charmeleon | 80    | 19        | 4.21053
Charizard  | 100   | 90.5      | 1.10497
Squirtle   | 43    | 9         | 4.77778
Wartortle  | 58    | 22.5      | 2.57778
Blastoise  | 78    | 85.5      | 0.912281
Caterpie   | 45    | 2.9       | 15.5172
... (791 rows omitted)

In [89]:
# nan is short for "not a number". It's a value that is a placeholder for "I don't know"
# you can use.where to get rid of nans
temp.where(3, are.above_or_equal_to(0)).sort(3, descending=True)

name     | speed | weight_kg | speed/weight ratio
Kartana  | 109   | 0.1       | 1090
Haunter  | 95    | 0.1       | 950
Gastly   | 80    | 0.1       | 800
Flabébé  | 42    | 0.1       | 420
Cutiefly | 84    | 0.2       | 420
Azelf    | 115   | 0.3       | 383.333
Cosmog   | 37    | 0.1       | 370
Comfey   | 100   | 0.3       | 333.333
Uxie     | 95    | 0.3       | 316.667
Rotom    | 86    | 0.3       | 286.667
... (771 rows omitted)

In [93]:
pokemon.where('weight_kg', are.above_or_equal_to(0)).column('weight_kg').mean()

61.378104993597958

In [96]:
# question: how does the speed of pokemon that are more likely to be female
# compare to the speed of pokemon that are more likely to be male?
temp = pokemon.select('name', 'percentage_male', 'speed')
temp

name       | percentage_male | speed
Bulbasaur  | 88.1            | 45
Ivysaur    | 88.1            | 60
Venusaur   | 88.1            | 80
Charmander | 88.1            | 65
Charmeleon | 88.1            | 80
Charizard  | 88.1            | 100
Squirtle   | 88.1            | 43
Wartortle  | 88.1            | 58
Blastoise  | 88.1            | 78
Caterpie   | 50              | 45
... (791 rows omitted)

In [100]:
temp = temp.with_column('percentage_female', 100 - temp.column('percentage_male'))
temp

name       | percentage_male | speed | percentage_female
Bulbasaur  | 88.1            | 45    | 11.9
Ivysaur    | 88.1            | 60    | 11.9
Venusaur   | 88.1            | 80    | 11.9
Charmander | 88.1            | 65    | 11.9
Charmeleon | 88.1            | 80    | 11.9
Charizard  | 88.1            | 100   | 11.9
Squirtle   | 88.1            | 43    | 11.9
Wartortle  | 88.1            | 58    | 11.9
Blastoise  | 88.1            | 78    | 11.9
Caterpie   | 50              | 45    | 50
... (791 rows omitted)

In [101]:
temp.where('percentage_female', are.above(50))

name       | percentage_male | speed | percentage_female
Nidoran♀   | 0               | 41    | 100
Nidorina   | 0               | 56    | 100
Nidoqueen  | 0               | 76    | 100
Clefairy   | 24.6            | 35    | 75.4
Clefable   | 24.6            | 60    | 75.4
Vulpix     | 24.6            | 65    | 75.4
Ninetales  | 24.6            | 109   | 75.4
Jigglypuff | 24.6            | 20    | 75.4
Wigglytuff | 24.6            | 45    | 75.4
Chansey    | 0               | 50    | 100
... (43 rows omitted)

In [103]:
temp.where('percentage_female', are.above(50)).column('speed').mean()

66.79245283018868

In [104]:
temp.where('percentage_male', are.above(50)).column('speed').mean()

68.953020134228183

In [110]:
# question: what are all the electric pokemon from generation 1?
temp = pokemon.select('name', 'type1', 'generation').relabeled('type1', 'type')
temp

name       | type  | generation
Bulbasaur  | grass | 1
Ivysaur    | grass | 1
Venusaur   | grass | 1
Charmander | fire  | 1
Charmeleon | fire  | 1
Charizard  | fire  | 1
Squirtle   | water | 1
Wartortle  | water | 1
Blastoise  | water | 1
Caterpie   | bug   | 1
... (791 rows omitted)

In [114]:
temp.where('type', are.equal_to('electric')).where('generation', 1)

name       | type     | generation
Pikachu    | electric | 1
Raichu     | electric | 1
Magnemite  | electric | 1
Magneton   | electric | 1
Voltorb    | electric | 1
Electrode  | electric | 1
Electabuzz | electric | 1
Jolteon    | electric | 1
Zapdos     | electric | 1

---

In [4]:
cereal = Table.read_table('data/cereal.csv')
cereal.show(15)

In [6]:
shelves = cereal.select('name', 'shelf', 'sugars')
shelves

name                      | shelf | sugars
100% Bran                 | 3     | 6
100% Natural Bran         | 3     | 8
All-Bran                  | 3     | 5
All-Bran with Extra Fiber | 3     | 0
Almond Delight            | 3     | 8
Apple Cinnamon Cheerios   | 1     | 10
Apple Jacks               | 2     | 14
Basic 4                   | 3     | 8
Bran Chex                 | 1     | 6
Bran Flakes               | 3     | 5
... (67 rows omitted)

In [8]:
shelf_1 = shelves.where('shelf', are.equal_to(1))
shelf_1

name                    | shelf | sugars
Apple Cinnamon Cheerios | 1     | 10
Bran Chex               | 1     | 6
Cheerios                | 1     | 1
Corn Chex               | 1     | 3
Corn Flakes             | 1     | 2
Frosted Flakes          | 1     | 11
Golden Crisp            | 1     | 15
Honey Nut Cheerios      | 1     | 10
Honey-comb              | 1     | 11
Multi-Grain Cheerios    | 1     | 6
... (10 rows omitted)

In [10]:
shelf_1.column('sugars').mean()

4.7999999999999998

In [11]:
shelves.where('shelf', are.equal_to(2)).column('sugars').mean()

9.6190476190476186

In [12]:
shelves.where('shelf', are.equal_to(3)).column('sugars').mean()

6.5277777777777777

In [14]:
cold_vs_hot = cereal.select('name', 'type', 'protein', 'fiber')
cold_vs_hot

name                      | type | protein | fiber
100% Bran                 | C    | 4       | 10
100% Natural Bran         | C    | 3       | 2
All-Bran                  | C    | 4       | 9
All-Bran with Extra Fiber | C    | 4       | 14
Almond Delight            | C    | 2       | 1
Apple Cinnamon Cheerios   | C    | 2       | 1.5
Apple Jacks               | C    | 2       | 1
Basic 4                   | C    | 3       | 2
Bran Chex                 | C    | 2       | 4
Bran Flakes               | C    | 3       | 5
... (67 rows omitted)

In [17]:
# what is the avg. amount of protein in the hot cereals in the dataset?
cold_vs_hot.where('type', are.equal_to('H')).column('protein').mean()

4.0

In [18]:
cold_vs_hot.where('type', are.equal_to('H')).column('fiber').mean()

1.2333333333333334

In [19]:
cold_vs_hot.where('type', are.equal_to('C')).column('protein').mean()

2.4864864864864864

In [20]:
cold_vs_hot.where('type', are.equal_to('C')).column('fiber').mean()

2.189189189189189

In [21]:
cereal

name                      | mfr  | type | calories | protein | fat  | sodium | fiber | carbo | sugars | potass | vitamins | shelf | weight | cups | rating
100% Bran                 | N    | C    | 70       | 4       | 1    | 130    | 10    | 5     | 6      | 280    | 25       | 3     | 1      | 0.33 | 68.403
100% Natural Bran         | Q    | C    | 120      | 3       | 5    | 15     | 2     | 8     | 8      | 135    | 0        | 3     | 1      | 1    | 33.9837
All-Bran                  | K    | C    | 70       | 4       | 1    | 260    | 9     | 7     | 5      | 320    | 25       | 3     | 1      | 0.33 | 59.4255
All-Bran with Extra Fiber | K    | C    | 50       | 4       | 0    | 140    | 14    | 8     | 0      | 330    | 25       | 3     | 1      | 0.5  | 93.7049
Almond Delight            | R    | C    | 110      | 2       | 2    | 200    | 1     | 14    | 8      | -1     | 25       | 3     | 1      | 0.75 | 34.3848
Apple Cinnamon Cheerios   | G    | C    | 110      | 2       | 2    | 180    | 1.5   | 10.5  | 10     | 70     | 25       | 1     | 1      | 0.75 | 29.5095
Apple Jacks               | K    | C    | 110      | 2       | 0    | 125    | 1     | 11    | 14     | 30     | 25       | 2     | 1      | 1    | 33.1741
Basic 4                   | G    | C    | 130      | 3       | 2    | 210    | 2     | 18    | 8      | 100    | 25       | 3     | 1.33   | 0.75 | 37.0386
Bran Chex                 | R    | C    | 90       | 2       | 1    | 200    | 4     | 15    | 6      | 125    | 25       | 1     | 1      | 0.67 | 49.1203
Bran Flakes               | P    | C    | 90       | 3       | 0    | 210    | 5     | 13    | 5      | 190    | 25       | 3     | 1      | 0.67 | 53.3138
... (67 rows omitted)

In [26]:
cereal.where('mfr', are.equal_to('K')).column('potass').mean()

103.04347826086956

In [27]:
cereal.where('mfr', are.equal_to('G')).column('potass').mean()

85.227272727272734

In [34]:
cereal.select('name').with_column(
    'carbs / sugars', cereal.column('carbo') / cereal.column('sugars')
).sort('carbs / sugars', descending=True).show()

C:\Users\ln015\AppData\Local\Temp\ipykernel_28500\1123899768.py:2: RuntimeWarning: divide by zero encountered in divide
  'carbs / sugars', cereal.column('carbo') / cereal.column('sugars')

In [38]:
cereal.column('sugars').mean()

6.9220779220779223

In [40]:
cereal.where('sugars', are.above_or_equal_to(9)).sort('rating', descending=True)

name                                   | mfr  | type | calories | protein | fat  | sodium | fiber | carbo | sugars | potass | vitamins | shelf | weight | cups | rating
Fruitful Bran                          | K    | C    | 120      | 3       | 0    | 240    | 5     | 14    | 12     | 190    | 25       | 3     | 1.33   | 0.67 | 41.0155
Fruit & Fibre Dates; Walnuts; and Oats | P    | C    | 120      | 3       | 2    | 160    | 5     | 12    | 10     | 200    | 25       | 3     | 1.25   | 0.67 | 40.917
Raisin Bran                            | K    | C    | 120      | 3       | 1    | 210    | 5     | 14    | 12     | 240    | 25       | 2     | 1.33   | 0.75 | 39.2592
Post Nat. Raisin Bran                  | P    | C    | 120      | 3       | 1    | 200    | 6     | 11    | 14     | 260    | 25       | 3     | 1.33   | 0.67 | 37.8406
Muesli Raisins; Dates; & Almonds       | R    | C    | 150      | 4       | 3    | 95     | 3     | 16    | 11     | 170    | 25       | 3     | 1      | 1    | 37.1369
Just Right Fruit & Nut                 | K    | C    | 140      | 3       | 1    | 170    | 2     | 20    | 9      | 95     | 100      | 3     | 1.3    | 0.75 | 36.4715
Crispy Wheat & Raisins                 | G    | C    | 100      | 2       | 1    | 140    | 2     | 11    | 10     | 120    | 25       | 3     | 1      | 0.75 | 36.1762
Corn Pops                              | K    | C    | 110      | 1       | 0    | 90     | 1     | 13    | 12     | 20     | 25       | 2     | 1      | 1    | 35.7828
Golden Crisp                           | P    | C    | 100      | 2       | 0    | 45     | 0     | 11    | 15     | 40     | 25       | 1     | 1      | 0.88 | 35.2524
Muesli Raisins; Peaches; & Pecans      | R    | C    | 150      | 4       | 3    | 150    | 3     | 16    | 11     | 170    | 25       | 3     | 1      | 1    | 34.1398
... (20 rows omitted)

In [41]:
cereal

name                      | mfr  | type | calories | protein | fat  | sodium | fiber | carbo | sugars | potass | vitamins | shelf | weight | cups | rating
100% Bran                 | N    | C    | 70       | 4       | 1    | 130    | 10    | 5     | 6      | 280    | 25       | 3     | 1      | 0.33 | 68.403
100% Natural Bran         | Q    | C    | 120      | 3       | 5    | 15     | 2     | 8     | 8      | 135    | 0        | 3     | 1      | 1    | 33.9837
All-Bran                  | K    | C    | 70       | 4       | 1    | 260    | 9     | 7     | 5      | 320    | 25       | 3     | 1      | 0.33 | 59.4255
All-Bran with Extra Fiber | K    | C    | 50       | 4       | 0    | 140    | 14    | 8     | 0      | 330    | 25       | 3     | 1      | 0.5  | 93.7049
Almond Delight            | R    | C    | 110      | 2       | 2    | 200    | 1     | 14    | 8      | -1     | 25       | 3     | 1      | 0.75 | 34.3848
Apple Cinnamon Cheerios   | G    | C    | 110      | 2       | 2    | 180    | 1.5   | 10.5  | 10     | 70     | 25       | 1     | 1      | 0.75 | 29.5095
Apple Jacks               | K    | C    | 110      | 2       | 0    | 125    | 1     | 11    | 14     | 30     | 25       | 2     | 1      | 1    | 33.1741
Basic 4                   | G    | C    | 130      | 3       | 2    | 210    | 2     | 18    | 8      | 100    | 25       | 3     | 1.33   | 0.75 | 37.0386
Bran Chex                 | R    | C    | 90       | 2       | 1    | 200    | 4     | 15    | 6      | 125    | 25       | 1     | 1      | 0.67 | 49.1203
Bran Flakes               | P    | C    | 90       | 3       | 0    | 210    | 5     | 13    | 5      | 190    | 25       | 3     | 1      | 0.67 | 53.3138
... (67 rows omitted)

In [46]:
healthiness = (cereal.column('vitamins') + 1) * (cereal.column('fiber') + 1) * (cereal.column('protein') + 1)
healthiness

array([  1.43000000e+03,   1.20000000e+01,   1.30000000e+03,
         1.95000000e+03,   1.56000000e+02,   1.95000000e+02,
         1.56000000e+02,   3.12000000e+02,   3.90000000e+02,
         6.24000000e+02,   5.20000000e+01,   5.46000000e+02,
         5.20000000e+01,   3.12000000e+02,   5.20000000e+01,
         7.80000000e+01,   1.56000000e+02,   1.04000000e+02,
         5.20000000e+01,   5.20000000e+02,   8.00000000e+00,
         1.56000000e+02,   2.34000000e+02,   1.56000000e+02,
         1.56000000e+02,   1.04000000e+02,   4.16000000e+02,
         6.24000000e+02,   6.24000000e+02,   5.20000000e+01,
         7.80000000e+01,   5.20000000e+01,   4.16000000e+02,
         4.16000000e+02,   4.16000000e+02,   1.04000000e+02,
         2.60000000e+02,   5.20000000e+01,   6.06000000e+02,
         1.21200000e+03,   7.80000000e+01,   3.90000000e+02,
         7.80000000e+01,   1.30000000e+02,   5.20000000e+02,
         5.20000000e+02,   4.16000000e+02,   2.34000000e+02,
         7.80000000e+01,   4.16000000e+02,   4.16000000e+02,
         2.60000000e+02,   7.28000000e+02,   8.08000000e+02,
         2.00000000e+00,   6.00000000e+00,   3.90000000e+02,
         2.22000000e+01,   6.24000000e+02,   3.64000000e+02,
         2.34000000e+02,   5.20000000e+01,   7.80000000e+01,
         1.20000000e+01,   2.00000000e+01,   1.60000000e+01,
         1.56000000e+02,   3.64000000e+02,   3.12000000e+02,
         3.03000000e+02,   2.02000000e+03,   1.61600000e+03,
         7.80000000e+01,   5.20000000e+01,   4.16000000e+02,
         4.16000000e+02,   1.56000000e+02])

In [49]:
cereal.select('name', 'sugars').with_column('healthiness', healthiness).sort('sugars').show(15)

In [52]:
min(cereal.column('calories'))

50

In [53]:
max(cereal.column('calories'))

160

In [54]:
cereal.sort('calories').show(1)

In [55]:
cereal.sort('calories', descending=True).show(1)

In [56]:
titanic = Table.read_table('data/titanic.csv')
titanic

PassengerId | Survived | Pclass | Name                                                | Sex    | Age  | SibSp | Parch | Ticket           | Fare    | Cabin | Embarked
1           | 0        | 3      | Braund, Mr. Owen Harris                             | male   | 22   | 1     | 0     | A/5 21171        | 7.25    | nan   | S
2           | 1        | 1      | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | 38   | 1     | 0     | PC 17599         | 71.2833 | C85   | C
3           | 1        | 3      | Heikkinen, Miss. Laina                              | female | 26   | 0     | 0     | STON/O2. 3101282 | 7.925   | nan   | S
4           | 1        | 1      | Futrelle, Mrs. Jacques Heath (Lily May Peel)        | female | 35   | 1     | 0     | 113803           | 53.1    | C123  | S
5           | 0        | 3      | Allen, Mr. William Henry                            | male   | 35   | 0     | 0     | 373450           | 8.05    | nan   | S
6           | 0        | 3      | Moran, Mr. James                                    | male   | nan  | 0     | 0     | 330877           | 8.4583  | nan   | Q
7           | 0        | 1      | McCarthy, Mr. Timothy J                             | male   | 54   | 0     | 0     | 17463            | 51.8625 | E46   | S
8           | 0        | 3      | Palsson, Master. Gosta Leonard                      | male   | 2    | 3     | 1     | 349909           | 21.075  | nan   | S
9           | 1        | 3      | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   | female | 27   | 0     | 2     | 347742           | 11.1333 | nan   | S
10          | 1        | 2      | Nasser, Mrs. Nicholas (Adele Achem)                 | female | 14   | 1     | 0     | 237736           | 30.0708 | nan   | C
... (881 rows omitted)