In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [2]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon = pokemon.where('generation', 1).select('name', 'type1', 'hp')
pokemon

name       | type1 | hp
Bulbasaur  | grass | 45
Ivysaur    | grass | 60
Venusaur   | grass | 80
Charmander | fire  | 39
Charmeleon | fire  | 58
Charizard  | fire  | 78
Squirtle   | water | 44
Wartortle  | water | 59
Blastoise  | water | 79
Caterpie   | bug   | 45
... (141 rows omitted)

In [3]:
pokemon.take(5)

name      | type1 | hp
Charizard | fire  | 78

In [6]:
pokemon.take(make_array(0, 3, 6, 24)) # deterministic sample

name       | type1    | hp
Bulbasaur  | grass    | 45
Charmander | fire     | 39
Squirtle   | water    | 44
Pikachu    | electric | 35